"use client";
import React from 'react'
import Head from 'next/head';

const Page = () => {
    return (
        <div style={{ paddingLeft: "5%", paddingRight: "5%" }}>
            <h1 className='font-semibold tracking-tight text-2xl' style={{ textAlign: "center", marginTop: "30px", marginBottom: "20px" }}>2257 Disclosure Statement – FansSecret</h1>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Introduction:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>While FansSecret does not produce or post any content, we comply with the requirements of 18 U.S.C. §§2257, 2257A, and 28 C.F.R. §75 ("Section 2257"). FansSecret is a secondary producer as defined in 28 C.F.R. §75.1(c)(2) and therefore under 28 C.F.R. §75.2(b) FansSecret must maintain detailed records of identifications of all people appearing in content for age verification and identification purposes. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}></p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Please See 28 C.F.R. §75.2(b)”</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>“(b) A producer who is a secondary producer as defined in §75.1(c) may satisfy the requirements of this part to create and maintain records by accepting from the primary producer, as defined in §75.1(c), copies of the records described in paragraph (a) of this section. Such a secondary producer shall also keep records of the name and address of the primary producer from whom he received copies of the records. The copies of the records may be redacted to eliminate non-essential information, including addresses, phone numbers, social security numbers, and other information not necessary to confirm the name and age of the performer. However, the identification number of the picture identification card presented to confirm the name and age may not be redacted.”</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}></p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>FansSecret cooperates with valid law enforcement information requests as required by law through admin@whiteshoe.ai.</p>

            <h1 className='font-semibold tracking-tight text-2xl' style={{ textAlign: "center", marginTop: "30px", marginBottom: "20px" }}>DMCA TAKEDOWN POLICY</h1>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Introduction</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>This DMCA Takedown Policy is solely for reporting infringing content on FansSecret.com. If you need help removing infringing material from other websites, please contact us separately.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>DMCA Notice & Takedown Policy and Procedures</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>We respect copyright holders' intellectual property rights and voluntarily comply with the Digital Millennium Copyright Act (DMCA) notice and takedown provisions. As a "Service Provider" under 17 U.S.C. § 512(k)(1) of the DMCA, we qualify for "safe harbor" protections from copyright infringement claims. We expect our users to respect intellectual property rights as well. This Notice and Takedown Policy governs how we handle copyright infringement claims involving content on our platform.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>How to Submit a Notice of Claimed Infringement</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>If you believe your copyrighted work has been published on FansSecret.com without authorization, please submit a notice to our Designated Copyright Agent with the following information:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	Your electronic or physical signature, as the owner or authorized representative of the copyright holder.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A description of the copyrighted work or intellectual property that you claim has been infringed.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A description of the location of the infringing material on FansSecret.com (including specific URLs, if possible).</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	Your contact information (address, phone number, and email).</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A statement of your good faith belief that the use of the material is not authorized by the copyright owner, its agent, or the law.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A declaration, made under penalty of perjury, that the information you provided is accurate and that you are the copyright owner or authorized to act on the owner's behalf.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Submit your Notice to: admin@whiteshoe.ai Designated Copyright Agent</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Note: This policy applies only to infringing content on FansSecret.com. Our Designated Agent is not authorized to accept or waive service of formal legal processes without prior permission.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>For further details on DMCA notification requirements, visit DMCA Requirements.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Abuse Notification</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Filing false DMCA notices or misrepresenting facts in a DMCA notice or counter-notification can lead to legal liability, including damages, court costs, and attorneys' fees under 17 U.S.C. § 512(f). These procedures apply only to copyright infringement claims—not to other legal issues or claims. We will investigate and take appropriate action against anyone abusing the DMCA process.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Takedown Procedure</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Upon receiving a valid DMCA notice, we will disable access to or remove the infringing material. If the notice is not fully compliant with DMCA requirements but meets certain minimum standards, we will attempt to contact the party to help them meet the necessary requirements. When a valid notice is received, we will notify the affected user and give them the opportunity to submit a counter-notification. Repeat copyright infringers may have their accounts terminated.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>DMCA Counter-Notification Procedure</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>If you believe that a notice of claimed infringement was erroneous or that your material was wrongly removed, you may submit a counter-notification under Section 512(g)(2) & (3) of the DMCA. The counter-notification must include:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A specific description of the material that was removed or disabled.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A description of where the material appeared on the site before removal (including URLs if possible).</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A statement that you have a good faith belief that the removal or disabling of the material was a mistake or misidentification.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	Your contact information (address, phone number, and email).</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>•	A statement that you consent to the jurisdiction of the Federal District Court in your location or in the service provider's jurisdiction, and that you will accept service of process from the original claimant.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Submit your counter-notification to: admin@whiteshoe.ai Designated Copyright Agent</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>All notices and counter-notifications must be in English. Non-compliant notices will be disregarded.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>After receiving a valid counter-notification, we will forward it to the original claimant and restore the content within 10-14 days unless we are informed that the claimant has filed a court action seeking an injunction.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Modifications to the Policy</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>We may modify or update this policy at any time. Users should check back regularly to stay informed of any changes.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Customer Service Requests</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Please note that the DMCA Agent is a private attorney and is not associated with FansSecret in any other capacity. For customer service, payment issues, or cancellation requests, please contact the site's customer service team directly.</p>

            <h1 className='font-semibold tracking-tight text-2xl' style={{ textAlign: "center", marginTop: "30px", marginBottom: "20px" }}>ANTI-SLAVERY AND ANTI-TRAFFICKING </h1>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>If you use our platform to do trafficking or slavery, we will work with law enforcement to bring you to justice. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Web 3 Services, LLC is the owner and operator of FansSecret (www.FansSecret.com) ("FansSecret" or the "Company"), a social platform that connects creators and fans. FansSecret is inclusive of creators from all backgrounds and supports creators in reaching their full potential, aligned with the Company’s values and goals.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>At FansSecret, we are committed to combating modern slavery. We are dedicated to making FansSecret the safest digital media platform and do not tolerate any form of modern slavery or human trafficking, whether on our platform, through our partnerships, or within our supply chain.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Our Commitment</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>FansSecret strongly opposes all forms of modern slavery and human trafficking. These practices are criminal acts and serious violations of human rights. Modern slavery includes various forms of exploitation, such as slavery, servitude, forced labor, and human trafficking, all of which involve depriving someone of their liberty for personal or commercial gain.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>In the context of content creation, human trafficking is when a trafficker uses fraud, coercion, deceit, blackmail, threats of violence, theft, or any other wrongful act in order to manipulate someone to perform content creation on the trafficker’s behalf. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>We are committed to operating with integrity and actively working to prevent modern slavery and human trafficking in all aspects of our business, including our relationships with creators and fans. We also prioritize treating all employees, partners, and vendors with respect, maintaining safe working conditions, and conducting business responsibly and ethically.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Responsibility for This Statement</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>Our Leadership holds overall responsibility for ensuring compliance with this commitment. Managers at all levels are responsible for ensuring their teams understand and adhere to this statement and our anti-slavery and anti-trafficking policies.</p>
        </div>
    );
};

export default Page;