"use client";
import React from 'react'
import Head from 'next/head';

const Page = () => {
    return (
        <div style={{ paddingLeft: "5%", paddingRight: "5%" }}>
            <h1 className='font-semibold tracking-tight text-2xl' style={{ textAlign: "center", marginTop: "30px", marginBottom: "20px" }}>Terms of Use</h1>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>BY USING OUR SITE, YOU AGREE TO THESE TERMS – PLEASE READ THEM CAREFULLY</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>1.	Introduction: These Terms of Use outline your use of FansSecret and establish your agreement with us. Key points to keep in mind:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	We reserve the right to update these Terms of Service at any time.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	If you subscribe to a service, it will renew automatically unless canceled.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	Your rights may vary based on where you live when accessing FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	In the event of a dispute, you must notify us and engage in mediation before initiating any legal action against us.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	These terms of use incorporate the other policies shared on FansSecret.com, including the Acceptable Use Policy, Anti-Trafficking Statement, Appeals Policy, Complaints Policy, Content Security Policy, Contract between Fan and Creator, DMCA Policy, Platform to Business Policy, Referral Program, and any other policies. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>2.	Interpretation: Throughout these Terms of Service:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	The term "FansSecret" refers to the platform, including access through the URL www.FansSecret.com, and also to the owner and operator of FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"We", "our", and "us" refer to Web 3 Services, LLC, which operates FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Business User" designates a User who uses FansSecret for business purposes, whether acting directly or through another party, including Referring Users.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Consumer" refers to any User who is not categorized as a Business User.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Content" means any material posted on FansSecret by a User, including photos, videos, audio, live streams, data, text, metadata, images, emojis, and more.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Agreement between Fan and Creator" refers to the terms governing each Creator Interaction.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Creator" refers to a User who shares Content on FansSecret for Fans to view.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Creator Earnings" refer to the portion of Fan Payments payable to a Creator after fees and taxes are applied.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Creator Interaction" describes interactions on FansSecret that grant access to a Creator's Content, including subscriptions, pay-per-view content, and other types of transactions between a Fan and Creator.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	“Credit” means dollar value purchased according to the Credit Purchase Agreement and assigned to Fan account that can be spent on content and creator interactions. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	“Credit Purchase Agreement” means the agreement governing user purchase and use of credits on the platform. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Fan" means any User who registers for an account and accesses Content via a Creator Interaction.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Fan Payment" refers to any use of Credit related to a Creator Interaction. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Include", "Includes", and "Including" are used in a non-limiting manner.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Indirect Sales Taxes" refers to statutory taxes applied to Fan Payments in applicable jurisdictions.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Notice", "Notify", and "Notification" mean any attempt to share information with you by sending a message to your FansSecret account, emailing you, sending a letter to your physical address, or reaching out via phone or text.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Referring User" refers to a User involved in the FansSecret Referral Program.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Subscription" is a Fan's binding agreement to access a Creator's Content for a set period, with automatic renewal unless canceled.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Subsidiary" means a legal entity controlled by Web 3 Services, LLC, either solely or in partnership with other subsidiaries.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Tax" refers to all forms of taxation, charges, levies, or withholdings in any relevant jurisdiction.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Terms of Service" refers to your legally binding agreement with us, including: (i) these Terms of Use; (ii) the Acceptable Use Policy; (iii) Referral Program Provisions; (iv) Platform to Business Regulation Provisions; (v) Complaints Policy; (vi) Appeals Policy; and (viii) Community Guidelines.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"Upload" refers to the act of posting, displaying, or sharing any material on FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>o	"User" refers to anyone using FansSecret, whether as a Fan, Creator, or both.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>3.	Who We Are and Contact Information: FansSecret is operated by Web 3 Services, LLC, a limited company registered in Wyoming. You can reach us via the email address provided on the website.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>4.	Changes to Terms of Service: We may modify any aspect of the Terms of Service without prior notice:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. To comply with applicable laws and regulations; and/or</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. To address risks related to FansSecret, our Users, or third parties.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>In other cases, we will notify you of changes, allowing you to delete your account before the changes take effect. By continuing to use FansSecret, you agree to the updated Terms of Service.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>5.	Changes to FansSecret: We reserve the right to alter, suspend, or deactivate any part of FansSecret at any time. We do not guarantee uninterrupted access to FansSecret or its Content.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>6.	Registration on FansSecret: By signing up for FansSecret, you accept these Terms of Service. If you do not agree, your only recourse is to avoid registering or to stop using the platform. We may deny account applications for any reason. To access FansSecret, you must create an account, providing a valid email address, a username, and a password, or authenticating through a third party.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. Fan Account Registration Requirements:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. You must be at least 18 years old.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>ii. You must be legally capable of entering into a contract.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iii. You must be legally allowed to join, view Content, and use FansSecret’s features.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iv. You must not have been convicted of any serious crime.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>v. You agree to pay for any required Creator Interactions as set forth in the Terms of Service and the Agreement between Fan and Creator.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>vi. You have passed a financial vetting process that will require the upload of some official financial document in your full legal name. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>If you do not meet these conditions, you are prohibited from using FansSecret. Additional information may be requested before account approval.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. Creator Account Registration Requirements:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. You must upload a valid ID and two recent photos of yourself.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>ii. You must add bank account details or a payment method.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iii. You must choose a payout option for Creator Earnings.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iv. You must submit age or identity verification whenever requested.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>v. Set a subscription price for your Fans, if applicable.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>vi. Upload Content for Users to view after subscribing to your account.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>vii. You must provide any additional information requested based on your location or nationality.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>7.	Adult Content: Some of the material available on FansSecret includes adult content. By accessing FansSecret, you acknowledge this and agree that we are not liable for any damage or loss related to how or where you choose to view this material.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>8.	Content – General Provisions:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. Your Content is not confidential, and you grant your Fans permission to view it for their personal and lawful use in line with any licenses you grant.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. You bear full legal responsibility for any Content you Upload. If someone else helps manage your account, this does not absolve you of responsibility. We have a direct relationship with you, not with third parties, and you must ensure all Content and account usage complies with these Terms of Service.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. You guarantee that all Content you Upload:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. Complies with these Terms and applicable laws.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>ii. Is owned by you (including intellectual property rights) or you hold the necessary rights and licenses to post and monetize it.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iii. If containing third-party material, you have secured the required rights, licenses, or consents.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iv. The Content is:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>1.	Of satisfactory quality based on any relevant description, price, or representation made in advertising.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>2.	Suitable for the Fan’s intended use, as you’ve been informed.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>3.	As you’ve described.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. You will indemnify us against any breach of the warranties in this section, meaning you will be held responsible for any resulting loss or damage.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. We do not control or endorse any User Content. While we reserve the right to remove Content that violates our Terms, we are not obligated to pre-screen or monitor it.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>f. You agree to act as custodian of records for all Content you Upload.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>9.	Fan Subscriptions and Purchases: This section applies to Creator Interactions, such as Subscription billing and renewals:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. Creator Interactions are governed by the Agreement between Fan and Creator. While we facilitate these Interactions, we are not a party to any contracts between Fans and Creators.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. Creators are responsible for setting pricing for their Content.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. All prices are listed and charged in USD against the Credit in the Fan account.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. Once a Creator is notified that a Creator Interaction has been confirmed, they must fulfill their part of the agreement. Creators are liable for any loss or damage we may incur due to a breach of this obligation.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. Fans purchase Credit according to the Credit Purchase Agreement and spend their credit by clicking on the relevant subscribe, pay, tip, or other buttons to initiate a Creator Interaction. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>f. Fans authorize us and our subsidiaries to provide payment information to third-party providers for processing credit purchase payments and payouts to creators.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>g. Payments will be taken for Subscriptions periodically, or immediately for other transactions. Fans agree to the charges being debited from their Credits or from provided payment details.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. If one payment method fails, we will attempt the payment through another provided method.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>j. By clicking ‘Subscribe,’ Fans agree to an automatically renewing Subscription unless there is no credit in the account, payment is declined, the price changes, auto-renew is disabled, or the account is closed. No further notice will be provided.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>k. Upon canceling a Subscription, Fans will continue to have access to the relevant Content until the current subscription period ends, after which no further payments will be taken.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>10.	Creator payouts:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. All Fan Payments will be received and processed by a third-party payment provider that we approve.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. Creators are entitled to the prices listed and paid for, less any applicable fees. Creators acknowledge that Fans are paying with Credits, that represent a discounted portion of the price actually paid to the platform for the Credits. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. Creator Earnings will only be available for withdrawal once they are reflected in your FansSecret account.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. To withdraw Creator Earnings from your FansSecret account, your account balance must meet the minimum payout requirement.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. All Fan Payments and Creator Earnings are denominated in USD, but may be made available for payout in USDT to cryptocurrency wallets or in USD to a bank account. FansSecret has no obligation to provide any particular payment method, but must at least one method. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>11.	Tax compliance:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. General: </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. Creators are responsible for managing their own tax affairs. Neither we nor any Subsidiary: (i) are responsible for advising you on your tax matters or for any general tax information provided on FansSecret or via email; or (ii) are liable for any Creator’s non-payment of taxes.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>ii. By using FansSecret as a Creator, you confirm that you have reported, and will continue to report in the future, all payments you receive in connection with your use of FansSecret to the relevant tax authority in your jurisdiction, as required by law.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iii. If you become tax non-compliant while holding a FansSecret account or if you are involved in any litigation, inquiry, or investigation regarding potential tax non-compliance in connection with your use of FansSecret, we reserve the right to close your account, restrict payouts, or limit earnings from your account.	</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. UK and EU-based creators are required to follow all applicable VAT rules.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. Compliance responsibility: It is your responsibility to ensure you make any necessary tax filings and pay any taxes due on your earnings from FansSecret. Failing to meet your tax obligations may result in the closure or suspension of your FansSecret account.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>12.	Our rights and obligations:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. We reserve the right to suspend or remove any content that may breach our Terms of Service or create any legal liability for Creators, Users, or FansSecret under any jurisdiction.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. We comply with laws that require us to take proportionate measures to quickly remove illegal content when it is discovered on FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. When reviewing content, we may use technology tools, including classifiers and AI/ML-enabled tools, to detect and remove content that violates our policies.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. Recommender systems may be employed to display Creator accounts that other users with similar subscription preferences have followed.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. We are not responsible for any claimed losses due to actions we take to suspend or remove content in accordance with our Terms of Service.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>f. Content and accounts may be suspended or deleted according to our Terms of Service, and we will attempt to notify you.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>g. If your account is terminated, your content will be handled according to our Privacy Policy, and you will lose access to it.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>h. We reserve the right to review any suspected misuse or illegal use of FansSecret and may cooperate with law enforcement in such cases.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. Information or records about your use of FansSecret may be disclosed to third parties in line with our Privacy Policy.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>j. We may change the third-party payment providers who process Fan Payments.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>k. Apart from content owned or licensed by Creators, all rights to FansSecret and its contents belong to us or our licensors.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>l. We own all rights to anonymized data related to your use of FansSecret and may use it for any lawful purpose.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>m. We reserve the right to choose how to communicate with you, including through email or messages posted to your FansSecret account.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>13.	What we are not responsible for:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. We do not control or endorse the content posted by users on FansSecret, nor do we guarantee its accuracy, legality, or reliability. We comply with applicable laws to remove illegal content once we are made aware of it. You may report illegal content using our Complaints Policy.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. We do not grant you any rights in relation to content.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. We are not responsible if others recognize your identity from the content you post.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. We are not responsible for any user-provided suggestions, comments, reviews, or requests.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. We do not guarantee that Creators or Referring Users will generate earnings on FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>f. We cannot guarantee that FansSecret is compatible with all devices and operating systems. It is your responsibility to ensure your technology is compatible.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>g. We are not responsible for internet availability, or issues with your hardware or software that affect access to FansSecret.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>h. We are not responsible for any lost, stolen, or compromised user accounts, email accounts, or passwords, or unauthorized transactions resulting from them.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. We are not responsible for the circulation of content that was posted in breach of the Terms of Service.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>5. Circumstances in which we may suspend or delete your account and/or content, pause Fan Payments, or withhold Creator Earnings:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. We may suspend or delete your account with 30 days' notice, at any time, for any reason.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. Without warning or notice, we may: (i) suspend or delete your account or content; (ii) pause Fan Payments; (iii) withhold part of your Creator Earnings; or (iv) refund or cancel Fan Payments, if:</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>i. You have seriously or repeatedly breached the Terms of Service;</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>ii. You attempt or threaten to breach the Terms of Service in a way that could seriously impact us or another user; or</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>iii. We suspect some or all of your earnings resulted from fraudulent activity.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. If we confirm any of the above, we may: (i) delete your account or content; (ii) forfeit part of your earnings; or (iii) refund or cancel Fan Payments. We will notify you and provide reasons for our actions.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. If you do not dispute our decision within six months of notification, you waive your right to dispute. You may dispute a Creator Earnings forfeiture through our Complaints Policy or appeal account termination through our Appeals Policy.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. If a lien, levy, or other encumbrance is placed on your earnings, we may withhold those earnings and pause or cancel Fan Payments. We have no obligation to make payments to your creditors.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>f. We may offset harm or losses caused by your breach of the Terms of Service using your Creator Earnings.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>6. Dispute Resolution and Attorney’s Fees</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. Any disputes arising out of or relating to these Terms of Service, including claims for breach, tort, or statutory violations, shall be resolved exclusively by binding arbitration administered by an arbitrator of FansSecret’s choosing under the rules of the American Arbitration Association. The arbitrator’s decision shall be final and binding.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. The prevailing party in any arbitration shall be entitled to recover all reasonable attorney’s fees, costs, and expenses, even if the awarded damages are nominal or no actual damages are awarded. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. By agreeing to these Terms, you waive the right to trial by jury and participation in class or collective actions.</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>6. Content Security</p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>a. The Content Security Policy is incorporated into these terms of use. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>b. You acknowledge and accept that all content you view on FanSecret will be embedded with your personal userID data, and that any discovery of content with your personal userID data outside the platform in any context, including but not limited to shared on other social platforms, shared in private messages, or personally stored on user devices, will constitute proof of unauthorized sharing of platform content in breach of the Content Security Policy and you will be liable for the damages caused by the breach as described in the Content Security Policy. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>c. You represent and warrant to FansSecret and other users that you will not share, reproduce, modify, post, copy, duplicate, download, screenshot, take a photo of a screen, or in any other way transfer content shared on FansSecret outside the platform. You acknowledge that any violation of this section would constitute a fraudulent act against both FansSecret and to the Creator who posted the content. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>d. You acknowledge and accept that any unauthorized sharing of platform content outside the platform will also constitute a theft of the content from the user who uploaded it. </p>
            <p className='font-semibold tracking-tight text-2xl' style={{ fontSize: '18px', fontWeight: "normal" }}>e. You indemnify FansSecret and its owners from any and all liability, claims, causes of actions, or other penalties that are triggered by your unauthorized sharing of platform content. </p>
        </div>
    );
};

export default Page;